### ISSUE TITLE
Set RS485 Mode Attribute Error

### ISSUE THREAD

**Issue by iclefirefly12** [whosaysni/robotframework-seriallibrary#1]
When you use your 'Set Rs485 Mode' Keyword you receive an the following Error:
'Attribute Error: 'bool' object has no attribute 'rts_level_for_tx'
I think this is because you set 'Serial.rs485_mode' to a Boolean value rather than an instance of the 'rs485.RS485Settings' object as stated in the pySerial documentation.
If you remove the Boolean value and the argument 'status' from your function it works because the function assumes the default RS485 settings. However a better solution would be to give the user the option of changing the parameters of 'rs485.RS485Settings'.

**Comment by whosaysni** [comment]
Hello @iclefirefly12,
On develop branch, Set RS485 Mode now accepts free keyword arguments (omitting arguments will disable the mode). Could you try it?

Thanks

**Comment by iclefirefly12** [comment]
Yes, that works fine. Cheers
