### ISSUE TITLE
Install error (Python >= 3.7)

### ISSUE THREAD

**Issue by tysonite** [whosaysni/robotframework-seriallibrary#10]
```
D:\>pip install robotframework-seriallibrary
Collecting robotframework-seriallibrary
  Using cached https://files.pythonhosted.org/packages/ce/e1/1e337dc84a20b9d92d7b243d16bb9f6fc0084967eca7454228bb546efec7/robotframework-seriallibrary-0.3.1.tar
.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tysonite\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tysonite
\\AppData\\Local\\Temp\\pip-install-vou9a4v7\\robotframework-seriallibrary\\setup.py'"'"'; __file__='"'"'C:\\Users\\tysonite\\AppData\\Local\\Temp\\pip-install-
vou9a4v7\\robotframework-seriallibrary\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.
close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\tysonite\AppData\Local\Temp\pip-install-vou9a4v7\robotframework-seriallibrary\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tysonite\AppData\Local\Temp\pip-install-vou9a4v7\robotframework-seriallibrary\setup.py", line 23, in <module>
        open(join(CURDIR, 'src', 'SerialLibrary', 'version.py'))).VERSION
      File "c:\users\tysonite\appdata\local\programs\python\python37\lib\imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 724, in exec_module
      File "<frozen importlib._bootstrap_external>", line 859, in get_code
      File "c:\users\tysonite\appdata\local\programs\python\python37\lib\imp.py", line 152, in get_data
        self.file = file = open(self.path, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'version'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by laurensmiers** [comment]
Seems to be fixed on the develop branch: #9 , but the version for pip is still the (old) 0.3.1 tag. If you just clone the repo and run "setup.py build/install" it should work.

**Comment by tysonite** [comment]
Nice, thanks. Time to release worldwide?

**Comment by jeremywood** [comment]
Would really like to see a release with this fix!

**Comment by oleszczyk** [comment]
Can't wait for this fix in official release! Do you know maybe when we can expect that?

**Comment by nopeppermint** [comment]
yes, please fix this!

**Comment by devnbhatt** [comment]
when installing via pip3 , giving error like this :

Collecting robotframework-seriallibrary==0.3.1 Downloading https://files.pythonhosted.org/packages/ce/e1/1e337dc84a20b9d92d7b243d16bb9f6fc0084967eca7454228bb546efec7/robotframework-seriallibrary-0.3.1.tar.gz ERROR: Command errored out with exit status 1: command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/setup.py'"'"'; __file__='"'"'/private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/pip-egg-info cwd: /private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/ Complete output (15 lines): /private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/setup.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses from imp import load_source Traceback (most recent call last): File "<string>", line 1, in <module> File "/private/var/folders/fq/z6b6csln1fn7l6y40g03s9sjtzwscs/T/pip-install-qdtns6ma/robotframework-seriallibrary/setup.py", line 23, in <module> open(join(CURDIR, 'src', 'SerialLibrary', 'version.py'))).VERSION File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source module = _load(spec) File "<frozen importlib._bootstrap>", line 696, in _load File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 724, in exec_module File "<frozen importlib._bootstrap_external>", line 859, in get_code File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 152, in get_data self.file = file = open(self.path, 'rb') FileNotFoundError: [Errno 2] No such file or directory: 'version' ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Does it mean that it is yet to be released supporting python 3.7 ?

**Comment by tysonite** [comment]
For anyone who wants to install robotframework-seriallibrary on Python 3.7+, use git repo instead of pypi:
```
pip install git+https://github.com/whosaysni/robotframework-seriallibrary.git@d5c33014acafc35f3190d345d422b43699a382f8
```

**Comment by whosaysni** [comment]
Thank you for posting issue, and terribly sorry for long absense.
0.4.1 should fix the issue. If you still have trouble, please reopen.
