### ISSUE TITLE
Unable to open serial port from SSH in Robot Framework

### ISSUE THREAD

**Issue by RalphC19** [whosaysni/robotframework-seriallibrary#11]
```
*** Settings ***
Documentation   Automation Test for BVT
Library         SSHLibrary
Library         SerialLibrary       encoding=ascii

Test Setup     Open Connection and Log In
Test Teardown  Teardown


*** Test Cases ***

Test1
    Execute Command And Verify Output
    Open Serial Port


*** Keywords ***

Open Connection and Log In
    Open Connection  ${HOST}
    Login            ${SSH_USERNAME}  ${SSH_PASSWORD}

Teardown
    Close All Connections

Execute Command And Verify Output
    [Documentation]    Execute Command can be used to ran commands on the remote machine.
    ...                The keyword returns the standard output by default.
    ${output} =        Execute Command  echo Hello SSHLibrary!
    Should Be Equal    ${output}        Hello SSHLibrary!
    Execute Command    sudo killall minicom

Open Serial Port
    Add Port   /dev/ttyUSB0
    ...        baudrate=115200
    ...        bytesize=8
    ...        parity=N
    ...        stopbits=1
    ...        timeout=999     # Dealing with the serial port at most for 999 seconds
```

I want to be able to SSH into a device and also open a serial port from that box. I usually ssh@box and type in "sudo killall minicom" to kill all existing processes and "sudo -D minocom /dev/ttyUSB0" to connect to the device in which I am promoted by the password of the ssh@box  then it allows me to serial into the board. The board then has a randomized user prompt, a password prompt, then after I enter those, I get the prompt.

**Comment by MartinHerren** [comment]
Unfortunately you don't give which part exactly doesn't work or what error message you get.

You mention doing `sudo minicom -D /dev/ttyUSB0` when doing the test manually. I haven't seen an option in the SerialLibrary to open the serial port with sudo or a specific user. So you probably need to ssh as an user with correct permissions to access the serial port (member of the dialout group usually) or adjust the permissions of the user you use.

Also you do a
```
    Execute Command    sudo killall minicom
```
the `Execute Command` command from the `SSHLibrary` has a sudo option so probably cleaner to do a
```
    Execute Command    killall minicom    sudo=True
```

**Comment by whosaysni** [comment]
Thank you for question,
You want to open serial port on remote host via ssh, right?

SerialLibrary affects only local host's serial device (where pyserial is installed)
To interact with remote device's serial port, you will need any of:
* use some port-forward to remote /dev/ttySomething to local tty or (virtual) serial port device.
* run RFW on remote host.

I'll close this issue because many days passed since OP(sorry). Feel free to reopen.
