### ISSUE TITLE
Connect to a System over Serial and run a Command

### ISSUE THREAD

**Issue by abmaazao** [whosaysni/robotframework-seriallibrary#13]
Hello Guys,
With Robot, I'd like to connect to a system (modem) over COM24 and execute command.
I created a robot Script (see below) using **seriallibrary**, the Robot ran with no errors but I didn't see those commands being executed in the remote system as I wish.  would it be possible to write the ggood robot script please?

Serial Ports Settings must be:  baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=1.0, xonxoff=False, rtscts=False, dsrdtr=False

Usually, I use Putty to connect to my system over Serial
once i'm connected into it, I write the command "AT+CGATT=0 ( or 1) and I hit "ENTER" to execute it

* Settings ***
Library           SerialLibrary

*** Variables ***
${ComPort}        COM24

*** Test Cases ***
ListComPorts
    @{ports} =    List Com Ports
    Log    ${ports[0].device}

AddPort
    Add Port    ${ComPort}

SetPortParameter
    Set Port Parameter    baudrate    115200

OpenPort
    Open Port    ${ComPort}

WriteData
    Write Data    AT+CGATT=0    encoding=ascii
    Send Break
    Send Break    0.5
    Read All And Log    loglevel=debug    encoding=ascii
    Write Data    AT+CGATT=1    encoding=ascii
    Send Break
    Send Break    0.5
    Read All And Log    loglevel=debug    encoding=ascii
    
ClosePort
    Close Port    ${ComPort}
    
*** Keywords *

##Thanks in Advance"

**Comment by whosaysni** [comment]
Hello,

You are sending AT+CGATT=1 then ENTER on Putty, so how about append CR or CRLF?

(I'll close this issue, but feel free to reopen if there are updates)
