### ISSUE TITLE
Sending arrow keys on serial port

### ISSUE THREAD

**Issue by fspegni** [whosaysni/robotframework-seriallibrary#5]
Hello,

I'm not able to send arrow keys on the serial port and get the result. This would be very helpful for testing behaviors like "fetch the last entry in the history file" (in my case the last command executed is returned from the device on the serial port after pressing the arrow-up key once).

Using a terminal (e.g. `minicom`) I can do this:
* open minicom with proper settings
* press the arrow-up key
* observe the command line sent previously to the device

I try to simulate it with `robotframework` and `seriallibrary` with the following test case:

    Library    SerialLibrary    encoding=ascii
    
    MyTest
        ${arrow_up} =    Set Variable    Esc[1A
        Write Data    ${arrow_up}
        ${output} =         Read Until

and at the end `${output}` will contain the characters `Esc[1A` instead of the last executed command. I guess my mistake is that I'm not escaping properly the special character sequence. If this is the case, could you please improve the documentation in order to explain how to do it? If this is not possible in the `seriallibrary`, would you consider covering this scenario?

**Comment by fspegni** [comment]
I figured out that in order to send the proper `Esc[A` I've to define `${arrow_up}` to be `\x1b[A` (following the "pythonese" encoding of `Esc[A`. Credits: https://stackoverflow.com/a/22398481/374430

My suggestion is that other users may benefit from an example covering this scenario, like the following:

```
Library    SerialLibrary    encoding=ascii

MyTest
    ${arrow_up} =    Set Variable    \x1b[A
    Write Data    ${arrow_up}
    ${output} =         Read Until
```

**Comment by whosaysni** [comment]
Hello,

I guess the command history recall is implemented on the minicom or something.

RFW-seriallibrary is not a terminal emulator. It sends data directly to com port attached to your device.

So if you get output as same as what you sent, it’ll be echoback from the port.

Afraid to say I won’t add the feature.
But since you can keep any data in a variable or file using RFW, you can easily write keyword like “Repeat Previous Command” or so.

**Comment by fspegni** [comment]
Just as a side note, the history recall function is not implemented by minicom, but the program that receivs the arrow keystroke returns the most recent command using a stack. In fact I can simulate this behavior even if minicom is not installed in the system. 

Note that in my scenario I didn't want to "implement" a history in the test (in which case your suggestion would make sense), but I was testing how the (already implemented) history in the queried terminal (attached to the serial port) was working.

I still suggest to add an example covering this scenario, where non-ascii characters are sent through the serial library
