### ISSUE TITLE
Error when Read Until is invoked with a string terminator

### ISSUE THREAD

**Issue by fspegni** [whosaysni/robotframework-seriallibrary#6]
If in my robot-framework test case I write:

    Test Bla
        Read Until  terminator=foo

then "foo" is passed as `bytes`, and thus I get the following error trace:

````
20190327 10:39:07.817 - FAIL - AttributeError: 'bytes' object has no attribute 'encode'
20190327 10:39:07.817 - DEBUG - Traceback (most recent call last):
  File "/home/XXX/.virtualenvs/atlc/lib/python3.6/site-packages/SerialLibrary/__init__.py", line 529, in read_until
    terminator = self._encode(terminator)
  File "/home/XXX/.virtualenvs/atlc/lib/python3.6/site-packages/SerialLibrary/__init__.py", line 177, in _encode
    return ustring.encode(encoding or self._encoding, encoding_mode)
````

At the moment the code in `SerialLibrary.read_until` is:

            if terminator != LF:
                terminator = self._encode(terminator)

First of all it seems incorrect that the invocation of `self._encode` does not forward the parameter `encoding` received by the `read_until` method. 

Second, if the `terminator` is an object of type `bytes` (as passed by `robotframework`), it makes no sense to encode it. Thus, I would suggest to amend the code as follows (if you don't seen any trouble):

        if terminator != LF and not isinstance(terminator, bytes):
            terminator = self._encode(terminator, encoding)

Does it make sense to you?

**Comment by monotaro-yasushi-masuda** [comment]
@fspegni 

Looks good, could you please write up a PR including tests?

**Comment by Diload** [comment]
This would also be fixed by this [pull request](https://github.com/whosaysni/robotframework-seriallibrary/pull/8).

It would probably be better to make a check, like in your example and entirely omit calling the _encode function for the items that doesn't need it but the solution in referenced PR is quick and works for all other occurrences of this problem.

**Comment by bahjat1993** [comment]
@Diload  i'm trying to install and download your pull request but it's complaining "FileNotFoundError: [Errno 2] No such file or directory: 'version'"

**Comment by drchopper** [comment]
@whosaysni could you please merge this issue?

Thanks
Tim

**Comment by whosaysni** [comment]
0.4.1+ has fixed this. Please try.
