### ISSUE TITLE
Python 3 support of multiple ports

### ISSUE THREAD

**Issue by yerpj** [whosaysni/robotframework-seriallibrary#7]
Hi guys,

First of all, thanks for this module, very helpful!

I got an error while porting my *.robot file to be executed in Python 3. 
Basically, I open a serial port, then I open a second one, switch to it, make some data exchanges and finally delete it:
```
TC1
    [Setup]    Open Primary Serial Port
    Write Data    Hello on Primary port\n
    [Setup]    Open Auxiliary Serial Port
    Switch Port    ${COMPORT2}
    Write Data    Hello on Secondary port\n
    Delete Port    ${COMPORT2}
    [Teardown]    Delete All Ports


Open Primary Serial Port
    Add Port    ${COMPORT}    baudrate=115200    bytesize=8    parity=N    stopbits=1    timeout=1
Open Auxiliary Serial Port
    Add Port    ${COMPORT2}    baudrate=115200    bytesize=8    parity=N    stopbits=1    timeout=1
```

It seems that `Delete Port    ${COMPORT2}` is raising the error "TypeError: 'odict_keys' object is not subscriptable". I tried running the same script with Python 2, everything works well. 
It seems that dictionary is not used similarly across Python 2 and Python 3.

**Comment by whosaysni** [comment]
Thanks for reporting issue. (and very sorry for late respond)
Fixed in 0.4.2. please try.
